# Generated by Django 3.0.3 on 2020-02-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200223_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedhomework',
            name='mark',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.FinishedHomework')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Mark'),
            preserve_default=False,
        ),
    ]
