# Generated by Django 3.0.3 on 2020-02-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200224_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedhomework',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='homework',
        ),
        migrations.AddField(
            model_name='mark',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FinishedHomework',
        ),
    ]
