# Generated by Django 3.0.3 on 2020-02-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_comment_finishedhomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.Lecture'),
        ),
    ]
