# Generated by Django 3.0.3 on 2020-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200225_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
