# Generated by Django 3.0.3 on 2020-02-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Mark'),
            preserve_default=False,
        ),
    ]
